### ISSUE TITLE
First draft for the intro scene with Shing's grandfather

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/Tales-of-Hearts-DS#10]
File: FSHT00P

**Comment by fortiersteven** [comment]
Translate Zex

![Image](https://github.com/lifebottle/Tales-of-Hearts-DS/assets/74146408/11bf3d70-a521-4d8d-b49c-0aab7eebbb29)

**Comment by fortiersteven** [comment]
Text going offscreen
![Image](https://github.com/lifebottle/Tales-of-Hearts-DS/assets/74146408/d96557ef-8516-477c-9440-96ae772d99ed)

**Comment by fortiersteven** [comment]
Text
![Image](https://github.com/lifebottle/Tales-of-Hearts-DS/assets/74146408/d38735fd-efef-47ab-afc1-6e7b183f06c8)

**Comment by fortiersteven** [comment]
![Image](https://github.com/lifebottle/Tales-of-Hearts-DS/assets/74146408/8dca9627-eb80-4178-8183-88cab3896c7b)

**Comment by fortiersteven** [comment]
Maybe we can reprhrase this one?
Dont know if "You fools, I'll be the longest living person in the world" ? would still be good

![Image](https://github.com/lifebottle/Tales-of-Hearts-DS/assets/74146408/06701a47-6ac7-4b6a-8f91-db71d8d9b1de)

**Comment by fortiersteven** [comment]
typo


![Image](https://github.com/lifebottle/Tales-of-Hearts-DS/assets/74146408/4cb45e85-2fa1-4b56-bff1-49a2b3def989)

**Comment by fortiersteven** [comment]
Missing dot


![Image](https://github.com/lifebottle/Tales-of-Hearts-DS/assets/74146408/c776ee04-0312-4714-be58-3d787f4bfb77)

**Comment by xsonicdragon** [comment]
> ![Image](https://private-user-images.githubusercontent.com/74146408/332132027-634b22e0-8aa1-49f9-87b9-97ed54032bfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODE2NjMsIm5iZiI6MTcxNzY4MTM2MywicGF0aCI6Ii83NDE0NjQwOC8zMzIxMzIwMjctNjM0YjIyZTAtOGFhMS00OWY5LTg3YjktOTdlZDU0MDMyYmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEzNDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMTEyOGY2ZjhiNDYzN2RkZDg3NTU0ZmQ3NWI5MDFiNDUwNzRhNDUyYjQ2ZTAxYTU0Y2MzOGE4M2U0MjE1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.duLlsq4w2GMBy1HkXpNNW6VzczWI7_S0I1E_cJvZHSw)

Moved "here" down to the third line.

**Comment by xsonicdragon** [comment]
> Missing dot
> 
> ![Image](https://private-user-images.githubusercontent.com/74146408/332132270-c776ee04-0312-4714-be58-3d787f4bfb77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODE2NjQsIm5iZiI6MTcxNzY4MTM2NCwicGF0aCI6Ii83NDE0NjQwOC8zMzIxMzIyNzAtYzc3NmVlMDQtMDMxMi00NzE0LWJlNTgtM2Q3ODdmNGJmYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDEzNDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZTlhNWI4NTAwMjNlMjNjOTI3YzljNDZkZmRjN2MwNjRlNmNmODllNmYwMTU5YjhiMmI2M2FjYzk0NWRhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U1cknyUopB7n2ITOOwEDP5m69eb565E7J2QGqZU6nAk)

Added the period - Maxle

**Comment by xsonicdragon** [comment]
Fixed all the issues you pointed out.
